### ISSUE TITLE
Would like to rename interface methods to conform with PSR-1, Section 4.3

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#10]
As per PSR-1, Section 4.3: "Method names MUST be declared in camelCase()"
Link: http://www.php-fig.org/psr/1/

I would like to go through rbac.php and rename all methods to fit the camelCase naming scheme.

All this entails is changing the first character to lower case, but this would be a good step in towards full PSR compliance.

This will not effect logic or code execution.

**Comment by abiusx** [comment]
it is good an important specially for single word methods.

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Sorry, I could use some clarification.

Are you saying it's good to move forward with the PSR implementation, or it's good to keep things the way they are because there's a good amount of single word methods?

If it's the latter, then I think we should just move forward with the PSR conversion. I don't feel too comfortable releasing something as PSR compliant if at least the interface isn't PSR compliant. We could always make it known that it's only PSR-0 compliant.

Another thought that I had is: if single word methods were a reason to not move towards full PSR compliance then we can make them two words, i.e. removeItem, listRoles, getPath, etc...

But I'm not sure it's worth doing that just to because we don't want single word lowercase method names.

I'm just thinking out loud. Let me know what you think.

**Comment by jburns131** [comment]
Not to beat a dead horse, but there is one more reason why I feel it's a good idea to follow through with this proposal.

Anyone that is familiar with PSR standards will see a method that's capitalized and think it's a class/object at first glance, as Classes are labeled in StudlyCaps style.

I know, not a biggie, but that's one of the reasons for standards. So you can glance at the code and understand what is what :-)

**Comment by abiusx** [comment]
it was the first thing not the second

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Cool, I'll add that to the todo list :-)

**Comment by jburns131** [comment]
I've finished this task.

I am sure that the public interfaces are now PSR-1 / PSR-2 compliant.

There might be a few stragglers in the back end hanging around as there were quite a few changes. I'll keep an eye out for anything as I go.

Closing This Issue.
