### ISSUE TITLE
The result of Rbac->Users->hasRole() is incorrect.

### ISSUE THREAD

**Issue by JKooll** [OWASP/rbac#102]
I want to use this Rbac->Users->hasRole() to check whether a User has a Role or not. But the result is true when I check a role which a User does not has it. I looked at the source code for this method and found a bug.
https://github.com/OWASP/rbac/blob/84d993cbc676a89ac33359b94fa2b90ff2519dbb/PhpRbac/src/PhpRbac/core/lib/rbac.php#L978-L983
I think this should change to:
```php
$R = Jf::sql ( "SELECT * FROM {$this->tablePrefix()}userroles AS TUR
			JOIN {$this->tablePrefix()}roles AS TRdirect ON (TRdirect.ID=TUR.RoleID)
			JOIN {$this->tablePrefix()}roles AS TR ON (TR.Lft BETWEEN TRdirect.Lft AND TRdirect.Rght)

			WHERE
			TUR.UserID=? AND TUR.RoleID=?", $UserID, $RoleID );
```

**Comment by abiusx** [comment]
I believe you are correct.
