### ISSUE TITLE
Roles->permissions() & Permissions->roles() only return its directly related permissions and roles

### ISSUE THREAD

**Issue by cw1427** [OWASP/rbac#111]
The function in  $rbac->Roles->permissions() & $rbac->Permissions->roles() only return its directly related permissions and roles,  but not also iterate its descendants related permissions and roles.

Would you please provide one interface to implement it?

**Comment by abiusx** [comment]
That's the intended behavior, as getting descendants can return the whole database for many roles and permissions (e.g root) and we don't want that.

Why do you need to get a list of all permissions or all roles?

**Comment by cw1427** [comment]
Have a bypass way to get all the permissions for a role.   By using get descendants() to get all the children id list, and fetch all of their permissions.
