### ISSUE TITLE
$rbac->Edit: Sqlite query fails when missing parameters.

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#12]
As the title says, sqlite gives an error when the last 2 parameters are missing/null.

This is due to sqlite not binding missing/null values. MySQL does not throw an error, it just returns 'false'.

The Edit method builds a $Data array and passes that on to EditData, which is in full.php. EditData then passes that on to the SQL/SQL_pdo.

We should check to make sure that $Data is not empty before executing EditData.

Old Code:

```
function Edit($ID, $NewTitle = null, $NewDescription = null)
{
    $Data = array ();
    if ($NewTitle !== null)
        $Data ['Title'] = $NewTitle;
    if ($NewDescription !== null)
        $Data ['Description'] = $NewDescription;
    return $this->{$this->Type ()}->EditData ( $Data, "ID=?", $ID ) == 1;
}
```

Proposed Change:

```
function Edit($ID, $NewTitle = null, $NewDescription = null)
{
    $Data = array ();
    if ($NewTitle !== null)
        $Data ['Title'] = $NewTitle;
    if ($NewDescription !== null)
        $Data ['Description'] = $NewDescription;

    if (!empty($Data))
        return $this->{$this->Type ()}->EditData ( $Data, "ID=?", $ID ) == 1;

    return false;
}
```

I've got the sqlite tests up and running, and this is the only test that fails on both Windows and Linux.

I have tested the proposed change on both platforms and all tests are green.

**Comment by abiusx** [comment]
you can set up database adapter to throw error or return them when they happen in Queries

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Doh, that's exactly what is happening:
https://github.com/OWASP/rbac/blob/dev/PSR/Unit_Tests/PhpRbac/src/PhpRbac/core/lib/jf.php#L68

I would like to propose that we remove the error on lines 70/71 and return 'false' so that sqlite behavior is consistent with MySQL behavior. This will not only make the functionality consistent between adapters, but it will also allow more consistent result sets, error handling and unit tests.

I was going to propose that we change the error to an exception, but that doesn't resolve the issue of jf::SQL returning different results for each adapter and the inconsistency of behavior that comes along with that.

**Comment by abiusx** [comment]
worksforme

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
I've replaced the error message with 'return false' and reverted 'Edit' back to it's original state.

All unit tests are green.

I've push the commit to github.

If everything looks good we can close this Issue.

**Comment by abiusx** [comment]
its good as long as unit tests succeed

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com
