### ISSUE TITLE
AddPath node creation

### ISSUE THREAD

**Issue by abiusx** [OWASP/rbac#16]
AddPath should return the number of nodes created, not the ID of the final node. That can be get by PathID later. AddPath omits nodes that exist, so the number of nodes that are actually created are important. The following code helps (rbac.php line 240):
            if (! $t)
            {
                $IID = $this->Add ( $p, $Description, $Parent );
                $Parent = $IID;
                $NodesCreated++;
            }
            else
            {
                $Parent = $t;
            }

```
        $index += 1;
```

**Comment by jburns131** [comment]
BaseRbac->addPath now returns number of nodes created. Closing Issue.
