### ISSUE TITLE
Users->Unassign only works with role ID

### ISSUE THREAD

**Issue by abiusx** [OWASP/rbac#17]
should be updated to this
       if ($UserID === null)
            throw new \RbacUserNotProvidedException ("\$UserID is a required argument.");
        if (is_int ( $Role ))
        {
            $RoleID = $Role;
        }
        else
        {
            if (substr ( $Role, 0, 1 ) == "/")
                $RoleID = jf::$RBAC->Roles->PathID ( $Role );
            else
                $RoleID = jf::$RBAC->Roles->TitleID ( $Role );
        }
        return jf::SQL ( "DELETE FROM {$this->tablePrefix()}userroles
        WHERE UserID=? AND RoleID=?", $UserID, $RoleID ) >= 1;

**Comment by jburns131** [comment]
I've made the needed changes and everything test ok. Closing this Issue.
