### ISSUE TITLE
Enhancement: Move *.sql files

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#23]
I feel the 'mysql.sql' and 'sqlite.sql' files should be more readily accessible in the case of a manual installation.

Proposed directory: PhpRbac/database/

**Comment by abiusx** [comment]
agreed.

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
I have moved the files 'mysql.sql' and 'sqlite.sql' from 'PhpRbac/src/PhpRbac/core/sql/' to 'PhpRbac/database/'.

Closing this Issue.
