### ISSUE TITLE
Enhancement: Update *.sql files, insert initial default data

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#24]
Currently there are two steps to manually creating and populating the initial database schema:
1. Use the proper 'mysql.sql' or 'sqlite.sql' file to create the database structure
2. Creating a script to call $rbac->reset(true)

I feel that the 'mysql.sql' and 'sqlite.sql' files should not only contain the database structure, but also the initial default data.

With this enhancement a manual database installation and setup will only be a one step process.

The *.sql files should be updated to include the insertion of initial default data.

**Comment by abiusx** [comment]
the problem is those functions rely on current date. How about adding a comment to the bottom of SQL files, and adding base data below that?
-A

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
I was planning on something similar to that.

The top of the scripts will have the 'CREATE TABLE' statements, and under that I will add 'INSERT INTO' statements.

I know MySQL has the 'UNIX_TIMESTAMP()' function which returns the current unix timestamp, and I'm sure that SQLite has a similar function.

The intent is to continue allow folks to import the *sql file, or copy the contents of the script and execute the statements using a GUI like phpmysql. Either way the *.sql files should contain only SQL statements and be independent of other scripting languages (PHP/Js).

Does this address your concern, or is there something else I need to be aware of while working on this?

**Comment by jburns131** [comment]
I've made what I think are the necessary changes. I have tested the *.sql files and encountered no problems.

Please let me know if you see an issue with this solution. If everything look satisfactory please feel free to close this Issue. Thanks!

**Comment by abiusx** [comment]
my only concern was table prefixes
the rest is good
-A

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
I have made sure to include a warning reminding the user to change the prefixes in the 'Installation' section of the new docs, so I don't think there will be any more issues than in the past.

I will go ahead and close this Issue.
