### ISSUE TITLE
SQLite Compatability: SQLite does not support 'RIGHT JOIN'

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#26]
PermissionManager::roles() and RoleManager::permissions() fail when using SQLite if $OnlyIDs is 'false' do to the 'RIGHT JOIN' in the SQL query.

SQLite does not support RIGHT JOINS: http://www.sqlite.org/omitted.html

We will need to rewrite these queries to use LEFT JOINS.

**Comment by abiusx** [comment]
I have no idea on the top of my head how to do that… Gotta read more.
-A

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
ok. I'm going to finish up a few unit tests then start looking into this also.

**Comment by jburns131** [comment]
All Unit Tests are passing. Closing Issue.
