### ISSUE TITLE
$rbac->Enforce seems to have multiple issues

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#3]
I may not understand the proper use of $rbac->Enforce, but here are my observations:
- If the check for jf::CurrentUser() passes, $rbac->Enforce does not send enough parameters to $this->Check()
- If the check for jf::CurrentUser() pass does not pass errors are thrown because jf::run does not exist
- If $this->Check() returns false errors are thrown because jf::run does not exist

**Comment by abiusx** [comment]
Enforce is supposed to either psas silently, or make the browser do 401 Not Authorized.

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Should we implement jf::run so it will trigger the 401/403?

Also, since we are removing all references to jf::CurrentUser() as per Issue #2, I would like to propose that:
- We add a second argument to Enforce, $user_Id, which will be a mandatory argument
- We create/throw an Exceptoin if $user_Id is empty/null
- We add $user_Id as the second parameter to the call to $this->Check()

**Comment by abiusx** [comment]
no need for the throw, just make it a mandatory argument
no need for jf::run, just do a header 401 and die.
-A

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
I've addressed this Issue in commit https://github.com/OWASP/rbac/commit/aebafee2bd35e3580aea34d0ff17306b0ae78cac

Please review and close Issue if everything looks good to you.
