### ISSUE TITLE
Open source website

### ISSUE THREAD

**Issue by sheldon** [OWASP/rbac#36]
Hi

I've come across a few problems on the phprbac.net website. I'd love to be able to send pull requests for those, especially for documentation fixes. Any chance of making that website open source? Perhaps on a new orphan branch of this repository even, I'd happily do the legwork if anyone wants to send me the relevant files in a zip file.

Cheers
Sheldon

**Comment by abiusx** [comment]
Hello Sheldon!
Thanks for stepping in.
I think open sourcing the website is a better idea, though I can send you the credentials if you wanna work online.
Jesse is in charge of those. I’ll ask him to open source the documentations and the rest of the website as well.
Thanks

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
I'll work on that today. Thanks!

**Comment by jburns131** [comment]
I've added the 'site/phprbac.net' branch, which contains the site files.

If you have any questions about how the doc pages are set up please let me know.

**Comment by sheldon** [comment]
:+1: Brilliant, thanks very much. I'll send through pull requests for any problems I spot.

Just starting on a new project using this system for access control. Hope we can contribute something useful back in for others.

**Comment by jburns131** [comment]
@sheldon:

We have created a new Github Organization to host PHP-RBAC related repos: https://github.com/FriendsOf-PhpRbac

I have moved the website to FriendsOf-PhpRbac: https://github.com/FriendsOf-PhpRbac/phprbac.net

Please for the new repo and send all PR's there.

Thanks!

**Comment by sheldon** [comment]
Thanks @jburns131, I've just posted a first pull request there.

Sorry for this completely off topic question: are you guys aware of an UI projects for managing phprbac? Something web based, but not tied to a CMS would be ideal.

**Comment by jburns131** [comment]
There isn't anything right now, but there has been discussion about it.

We'd love to have an administrative UI eventually. If that's something you'd like to play around with let us know and we can create a topic branch for you to send pull requests to.

Any help would be appreciated on that front :-)

**Comment by sheldon** [comment]
Well, I really like the demo page. Was thinking something similar, but
dynamic for adding/removing nodes in both trees. I might have a go in some
spare time, d3.js might have the right tool for the job.

Cheers again for opening up the website, it's great to be able to share
work.

**Comment by jburns131** [comment]
The code (not the data) for the demo is in the 'phprbac.net/demo/' folder, so feel free to take a look and see if there's anything in there that might help.

**Comment by bblue** [comment]
I started some time ago to add a config module for rbac to my own website, no progress in quite some time, but maybe I can have something to chip in here as well.

![rbac](https://cloud.githubusercontent.com/assets/6132918/2630395/8de860ce-be48-11e3-9628-4b35d76aaded.png)

**Comment by sheldon** [comment]
Looks pretty nice @bblue. What did you use for drawing the graph?

**Comment by bblue** [comment]
It's actually just pure css, a slightly modified version of the example found here: http://thecodeplayer.com/walkthrough/css3-family-tree. I have added some elements to allow selection of nodes and highlight of selected node' sub-nodes, as well as a hover balloon for description. 

It looks tidy in that picture, but I am not sure I will keep it. The moment the tree grows or the browser is narrower the structure breaks. At least it needs some javascript to keep it rendering correctly, but then an all-out js family tree would probably be simpler. You can test this yourself in the website linked above by reducing your browser window.

Speaking of trees, what I am missing from RBAC is a feature to select a node and all it's children and children's children, returned in an array I can use for a tree. I suppose a function similar to `$rbac->Permissions->Descendants` could be used if it returned a multidimensional array instead. I currently use a recursive function for checking children of each node, but it is not a very efficient way of doing it.

Edit: I see that my function request is already an open issue #9

**Comment by jburns131** [comment]
Just to reiterate, I have moved the website code to it's own repo under the "FriendsOf-PhpRbac" Github Organization: https://github.com/FriendsOf-PhpRbac/phprbac.net

Closing this Issue.
