### ISSUE TITLE
$rbac->Permissions->Roles calls undefined method '$this->Permission_ID'

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#4]
If you look at the first if statement of $rbac->Permissions->Roles (rbac.php) you'll notice a call to the undefined method $this->Permission_ID:

```
if (! is_numeric ( $Permission ))
    $Permission = $this->Permission_ID ( $Permission );
```

I was wondering if we should implement $this->Permission_ID.

**Comment by abiusx** [comment]
it should change a path or title to an ID, for convenience

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Would you like to me to work on an implementation for $this->Permission_ID and submit it for review before committing it to the development branch?

Initial Thoughts/Proposal:
- I would think that we should name it GetId (similar to GetTitle), and create a wrapper around PathId and TitleId. This way we can use this as a BaseManager class that can be used for both Permissions and Roles in the future.
  
  We can check for a leading / (slash) and execute PathId. If there is no leading slash we can execute TitleId.

The code in $rbac->Assign is a good example of the above proposal.

**Comment by abiusx** [comment]
good idea

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
I have created a 'getId' method and the Unit Tests to go along with it.

I have also altered $rbac->Permissions->roles() and $rbac->Roles->Permissions to take advantage of 'getId'.

**Comment by jburns131** [comment]
The unit tests are passing with no problems using the mysql tests on both linux and windows, yet for some reason a couple tests fail using sqlite.

It's odd because $rbac->Permissions->roles() and $rbac->Roles->Permissions fail when calling 'PathId' through 'getId', yet the 'PathId' unit tests pass on their own. This leads me believe it's my implementation of 'getId'.

I'm sure I'm missing something minor. Maybe a fresh pair of eyes will be able to pick it out quickly.

To run the unit tests, execute either 'sqlite_tests.bat' or 'sqlite_tests.sh', depending on the OS you're using. You don't need to execute from a command line as each script waits for a key press at the end of execution so you can review the results.

**Comment by abiusx** [comment]
I realize now that Permission_ID is from the earlier version of code I had before. I beleive the solution I took for roles is a good one, creating two different queries instead of running two queries to first get the ID and then perform the query.

What say you?

**Comment by jburns131** [comment]
I just realized that there was already a 'getID' method in the 'FullNestedSet' class.

Need to look at this again.

**Comment by jburns131** [comment]
I have renamed my new BaseRbac::getId() to BaseRbac::returnId().

I have created the necessary Unit Tests and all tests pass.

Closing Issue.
