### ISSUE TITLE
Pass PDO instance as adapter.

### ISSUE THREAD

**Issue by Snooze-** [OWASP/rbac#41]
It would be beneficial if the database connection can be passed as a PDO object that's already been initialised.

This makes sense for applications where the pdo object has already been created and connection details don't have to be looked up again. It's also useful for PDO objects that are created using more complex connection mechanisms than the usual host, username, password.

As a practical example, I would like to make use of PDO MySQL's SSL features (documented in the [php manual](http://php.net/pdo_mysql)), but I'm not currently able to do so due to the limitations of the way database connections are handled by PhpRbac.

**Comment by abiusx** [comment]
Can’t you just replace the PDO object inside the wrapper with yours?

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by Snooze-** [comment]
I could replace Jf::$Db with my own connection, but Jf.php includes setup.php which always tries to connect with $host, $db, $user, $pass. I could change setup.php, but that is difficult, because I'm using composer to pull in PhpRbac, so every time there's an update I would have to make the change again.

If I could pass the PDO object to the Rbac constructor, I could use my own pdo object without having to modify any of the files pulled in composer.

**Comment by Snooze-** [comment]
Thank you.

I'll use the same solution mentioned in #40.
