### ISSUE TITLE
can some one tell me about the leftId and rightId meanings？

### ISSUE THREAD

**Issue by joostshao** [OWASP/rbac#42]
can some one tell me about the leftId and rightId meanings？
CREATE TABLE IF NOT EXISTS `rbac_permissions` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Lft` int(11) NOT NULL,
  `Rght` int(11) NOT NULL,
  `Title` char(64) COLLATE utf8_bin NOT NULL,
  `Description` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `Title` (`Title`),
  KEY `Lft` (`Lft`),
  KEY `Rght` (`Rght`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=5 ;

**Comment by abiusx** [comment]
This is to model Nested Set, a model for hierarchicaly presenting data in SQL. 
http://en.wikipedia.org/wiki/Nested_set_model

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by joostshao** [comment]
yes i know the Nested Set　model, thank you
