### ISSUE TITLE
No joy with install.php

### ISSUE THREAD

**Issue by benoliver999** [OWASP/rbac#48]
I get my credentials in, hit submit and all I get is a blank screen. Any suggestions as to what could be going wrong?

I'm:
- Using mysql (mariadb)
- Getting the code from the sourceforge download (2.0)

**Comment by abiusx** [comment]
enable error reporting on your PHP to see the error thats happeninng?
-A

**Comment by benoliver999** [comment]
Did a fresh install and can't reproduce the problem. Sod's law... Thanks for getting back to me anyway.

**Comment by abiusx** [comment]
You’re welcome. Please let us know if you had any more troubles, or any feedbacks.
-A

**Comment by benoliver999** [comment]
I hate to dig up old issues, but I'm getting a similar thing on another install, this time I can't fix it. Output:

```
Notice: Unable to prepare statement: INSERT INTO phprbac_rolepermissions     (RoleID,PermissionID,AssignmentDate) VALUES (?,?,?), reason: Table 'regenerysdb.phprbac_rolepermissions' doesn't exist in /var/www/PhpRbac/src/PhpRbac/core/lib/Jf.php on line 149

Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/PhpRbac/src/PhpRbac/core/lib/Jf.php on line 159

Fatal error: Call to a member function execute() on a non-object in /var/www/PhpRbac/src/PhpRbac/core/lib/Jf.php on line 160
```

**Comment by abiusx** [comment]
Please let us know the steps to reproduce this, and also some system information would be useful.
Thanks

**Comment by benoliver999** [comment]
Debian install on an EC2 instance. Using MariaDB. PhpRbac directory is in the site root aka http://mysite.com/PhpRbac/install.php

The database already has a 'users' table.

I fill out install.php, and get the error.

**Comment by abiusx** [comment]
what kind of database and PHP environments?

**Comment by benoliver999** [comment]
PHP Version 5.4.4-14+deb7u14
Using mysqli socket on the form, PHPinfo spits out mysqlnd 5.0.10 - 20111026 as API version.

Can't think of much else to say, the DB itself is a simple MySql job, with InnoDB as the storage engine.

Anything else you need to know give me a shout.

**Comment by abiusx** [comment]
thats weird…
Can you email the copy of code that you have to me, so that I can try to reproduce? I can’t reproduce using current code.

**Comment by benoliver999** [comment]
http://pastebin.com/ZjG7Ekzd

That's the install.php

**Comment by abiusx** [comment]
I don’t believe the error is in there. It just gets your creds. The library does the installation.

**Comment by benoliver999** [comment]
I'm going to go over it again, I'm missing something obvious, I'll figure it out.

**Comment by tekjau** [comment]
Got the same error on CentOS release 6.5 (Final), PHP 5.4.32, MariaDB 10.0.10, using MySQLi driver. Using MySQL shows installation done but no table created eventually.

**Comment by jburns131** [comment]
Sry, guys, I've been away for a little bit. Let me become more familiar with this ticket and I'll spend some time looking into this today.

I am in the middle of updating the install script, so I will either patch the current one or finish up the next version of the installation if it isn't going to take too long.

**Comment by abiusx** [comment]
Error reporting enabled?
