### ISSUE TITLE
Method to return users

### ISSUE THREAD

**Issue by bblue** [OWASP/rbac#49]
Similar to Rbac->Permissions->roles() there should be a Rbac->Roles->**users()** function, maybe even a Rbac->Permissions->users() function.

Something you would consider adding?

**Comment by abiusx** [comment]
Are you interested in direct assignments between users and roles, or indirect ones?

**Comment by bblue** [comment]
That is a good question, I had not considered that yet. I suppose you could need both, depending on the application.

Personally I was looking to trigger a notification upon a "new user"-event to the 'UserAdmin' role members. In this specific case I would be looking for direct assignments, but I can definitely see a use for indirect ones as well.

**Comment by abiusx** [comment]
I didn’t understand your use case, can you elaborate?

**Comment by bblue** [comment]
I just need the users directly assigned to a role, for now.

**Comment by abiusx** [comment]
that would be a very simple SQL query,
as users and roles are connected in a table rbac_userroles :

UserID  RoleID  Timestamp

x       y       time

You can just make a simple query there, or wait for us to add the feature and tests and all :D
If you have trouble with the query, let me know to help.

**Comment by bblue** [comment]
I have no trouble making the method and sql call myself, but I figured it would be a nice addition to the project.

It would be more 'tidy' to have it as part phprbac itself, but I'll make a wrapper class in the meantime.

**Comment by abiusx** [comment]
I personally decided not to include those to prevent bloats, since I couldn’t find a use-case for it.
RBAC system is in charge of access control and authorization, you probably are going to do some of your application logic by the roles in the RBAC system, which is not meant for it.
Am I right?

**Comment by bblue** [comment]
You are correct. I suppose I will be breaking the separation of concerns principle if using rbac for this.I now understand why you did not include it.

**Comment by bblue** [comment]
I am not looking to reopen this issue, but I would like to ask how a related issue should be solved. Hopefully you will follow my line of thought.
- If only using RBAC for access control and authorization I would need some sort of usergroup feature/layer to tag i.e. administrators. 
- Upon adding a user to the administrator group I would like to also provide the user with the rbac ROLES that an administrator should have.
- Simple enough, I create a method to add a user to the admin group and invoke rbac within that method to assign correct permissions.

And here comes the problem:
- What if I later remove the user from the administrator group. I _could_ strip the rbac roles as assigned before, but how do I tell if the user received a specific role from another usergroup? I could end up stripping the user of roles he should have had still.

The obvious solution would be to strip all roles, and reassign the roles as per his usergroup memberships, but that comes with its own set of issues. The main being that I then would be forced to manage all roles via usergroups, not user IDs.
