### ISSUE TITLE
$rbac->EntityType->AddPath(): Would like to find alternative to assert()

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#5]
I would like to find an alternative error handler to the call to assert.

**Comment by abiusx** [comment]
this assert should logically never fail. have you found a case?

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
If you pass a string that does not have a leading slash to the first argument of AddPath the assert fails and issues a php warning.

Example:

```
$rbac->Roles->AddPath('roles_1');
```

Result:

```
Warning: assert(): Assertion failed in /path/to/lib/rbac.php on line 210
```

My Thoughts/Proposed Solutions:

I think there are two ways we can go with this:
- Add a leading slash if there is one missing and continue execution
- Keep the "leading slash" requirement and replace the assert with production level error handling, i.e. throw an Exception that can be handled properly if so desired by PhpRbac users

**Comment by abiusx** [comment]
its a good choice, throw the exception and update phpdoc

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com
