### ISSUE TITLE
Installation... Cannot Modify Headers

### ISSUE THREAD

**Issue by Jester428** [OWASP/rbac#52]
(headers already sent by...) 
  Basically, the install.php - im obviously missing something here, please correct me - is full of output HTML... so when it says "header" (relocate to other page) it's a very unhappy bunny.
  What am i missing here?
/PhpRbac/install.php  returns : 

"Warning: Cannot modify header information - headers already sent by (output started at /var/www/[...pathto...]/PhpRbac/install.php:20) in /var/www/[...pathto...]/PhpRbac/install.php on line 235"

Now, when i put my site online (also was full of such holes) i had to redesign a little to get all the "location:xxxxx" and "header:xxxxxx" stuff to actually work - and not break the page load...

I went about fixing all that 1 at a time, and am fine with the outcome... 
  But now here again, the same issue...
  Im such a noob.
  AM I MISSING SOMETHING HERE?

**Comment by Jester428** [comment]
btw, i should have mentioned, this first occurs (and will likely later in other scripts) in install.php WHEN i hit go on database info. 
  The db info is fine, im sure of it. ntm quite obviously unrelated. 
Thanks for a miracle product (from what ive read) and for your help getting me started!

**Comment by jburns131** [comment]
We have decided that any supporting tools/functionality for PHP-RBAC will be hosted under the "FriendsOf-PhpRbac" Github Organization (https://github.com/FriendsOf-PhpRbac).

As an installation script is not part of the core library I have removed the installation script and will decide which proposed installation tool to host on "FriendsOf-PhpRbac" at a later date.
