### ISSUE TITLE
$rbac->Permissions->Roles and $rbac->Roles->Permissions return null when second parameter is null

### ISSUE THREAD

**Issue by jburns131** [OWASP/rbac#7]
The doc block states that if the second parameter equals null the the method will return a two dimensional array. "the two dimensional array would have ID,Title and Description of Role/Permission".

Right now both methods return null if the second parameter is null.

I believe we need to fix this.

**Comment by abiusx** [comment]
and it would be better to return objects instead of assoc arrays

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Just to make sure I understand you:

We should remove the second argument ($OnlyIDs = null) and just return an Object will all pertinent properties, i.e. $object->id, $object->title and $object->description.

**Comment by abiusx** [comment]
or branch it into two different functions, one for each

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
From Issue #6

jburns131 commented:

I have one concern regarding returning an object for this method. In either case we will be returning data for multiple items (every roll assigned to a user). I think we should probably stick with the array, because if we return an object it will still contain multiple items and in essence still be a multidimensional array.

I think if we were to return a single entity then an object would be ideal, but I'm not too sure about multiple entities. That sounds like the job and purpose of an array.

Let me know what you think.

abiusx commented:

hmm thats a sound point. lets return arrays, they are easier to convert into objects, but one should definitely know what indexes will be in the array. -A

**Comment by jburns131** [comment]
I have created a 'getId' method and updated $rbac->Permissions->roles() and $rbac->Roles->Permissions to take advantage of 'getId'.

I just briefly looked at this issue before working on it and spaced what we talked about in this ticket after taking a breather from it and coming back to it. So the solution I've committed to the repo is the original intent of the methods in question.

What I did was I implemented the 'getId' method, updated both of the above mentioned methods to take advantage of it, and also fixed the SQL queries for the above mentioned methods. The reason that 'null' was returned when the second parameter is false is because the 'ORDER BY' clause was incorrect.

See the commit diff to see the changes to the queries.

Right now the $rbac->Permissions->roles() and $rbac->Roles->Permissions methods will return an array of ID's if the second parameter ($OnlyIDs) is true.

If the second parameter ($OnlyIDs) is false, the array returned will be in the following form (for a single item):

```
array (size=1)
    0 => 
        array (size=3)
        'ID' => string '3' (length=1)
        'Title' => string 'roles_2' (length=7)
        'Description' => string '' (length=0)
```

This was the original intent of the methods mentioned above.

If this solution is satisfactory please let me know. If not I'll work on a different solution.

**Comment by abiusx** [comment]
Seems good to me. Time to close the issue.

**Comment by jburns131** [comment]
Thank you. Closing issue.
