### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by taiidani** [OWASP/rbac#76]
The http://www.phprbac.net website is currently down.

<img width="744" alt="screen shot 2016-02-25 at 10 36 41 am" src="https://cloud.githubusercontent.com/assets/902500/13329997/b1933116-dbab-11e5-8848-15d9ac2d646b.png">

**Comment by abiusx** [comment]
Yes the domain has expired, we are working on it.
You can access it from http://37.48.90.86/~phprbac/ http://37.48.90.86/~phprbac/ atm.
-A

**Comment by tchalvak** [comment]
This is no longer an issue!
