### ISSUE TITLE
GUI installer for SQLite

### ISSUE THREAD

**Issue by taophp** [OWASP/rbac#78]
I'm pleased to see that PHP-RBAC supports SQLite database as back-end. But the GUI install seems to not handle it properly. When I set the "Database Adapter" field to "SQLite", no other fields changes. But they make no sense for SQLite. I think I do not have to explain why the "Database Host Name/IP" does not mean anything in this case.

So you should _at least_ document that the GUI installer is not the current correct way to set a SQLite database.

**Comment by abiusx** [comment]
Is it impossible to install using GUI for SQLite? Maybe a piece of JS code to hide those fields is the trick.
-A

**Comment by taophp** [comment]
> Maybe a piece of JS code to hide those fields is the trick

Yes, that was exactly what I was thinking about. And some JS also to show the fields required to set up SQLite. And it should be easy. But will this be enough ?
I did not have any time to dive in the code, but I fear that some PHP is also required and that the SQLite option was only left as a reminder. Even in this case, the required changes are trivial. I may fork, fix and  request a pull if I have a few time.

**Comment by taophp** [comment]
Well, I just had a quick look to the `install.php`. It seems messy code to my eyes. I understand why the SQLite install is not yet implemented. I may completely rewrite it if I do something.

**Comment by taophp** [comment]
Oh, I get it: line 262, the Database Name field is used for the SQLite filename. So the other fields, required by the UI, may be filled with some mess, and the install should work.
