### ISSUE TITLE
Support UUID ?

### ISSUE THREAD

**Issue by taophp** [OWASP/rbac#80]
In both `mysql.sql` and `sqlite.sql` files, I read that the column `UserId` is set to receive integer data only. That may seem reasonable at first glance, but integers are not the only way to manage ids. There is [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) for example. Some applications, working at large scale in a distributed way, may use UUID instead of integer for good reasons.

As `UserID` is expected to be a external data for your lib, I think you should remove this limitation. So my questions:
1. have you, do you, will you consider to support UUID ?
2. do you think there is some other changes required somewhere in the code or only `mysql.sql` and `sqlite.sql` may be fixed ?

Cheers !

**Comment by abiusx** [comment]
Any datatype with auto-increment should work for that field.
However, I don’t think the library is ready for distributed use. It might need revising at all levels to make sure it works in a distributed manner.

**Comment by taophp** [comment]
Well, UUID are not auto-increment AT ALL. They have been invented to solve some issues related to auto-increment. They are 128 bits strings, like this `123e4567-e89b-12d3-a456-426655440000`

**Comment by abiusx** [comment]
I am aware of what they are.
Now that I think about it, the userid field is an external link, and doesn’t need to conform to any specific format. It is not generated inside the library.
It can safely be converted to a string format, albeit adding performance overhead.
-A

**Comment by taophp** [comment]
> I am aware of what they are.

I thought you are !
