### ISSUE TITLE
What is the minimal php requirements?

### ISSUE THREAD

**Issue by erdvillegas** [OWASP/rbac#81]
Hi everyone, I'd like to know what the minimal php requeriments are because I'm developing a system for an old php version (5.2.0) using cacke php as a framework, so it's out of my hands to upgrate it.

Thanks in advance

**Comment by abiusx** [comment]
I don’t think anything after PHP 5.2 is used. Maybe the wrapper interface has some PHP 5.3 elements, but you should be able to unwrap them pretty easily.
The library has been tested inside Linux kernel as well, so should have minimal dependencies.

**Comment by erdvillegas** [comment]
Well, I'll check it. Thank you

**Comment by tchalvak** [comment]
With the release of php 7, it'd be nice to know whether it's upwards compatible as well.  Composer allows setting the required php versions in composer.json, e.g.

```
"require": {
        "php": ">=5.6.0",

```

**Comment by erdvillegas** [comment]
Thanks for the help
