### ISSUE TITLE
{Entity}->children() returns empty

### ISSUE THREAD

**Issue by Mann-o** [OWASP/rbac#82]
I just want to point out that I have never had any problems with PhpRbac up until now - it is an excellent solution.

Anyway, my employer gave me a macbook and in order to continue working on a site I have utilised PhpRbac on before I downloaded all of the files from the webserver and exported the SQL database/tables (MySQL) to my local machine.

Everything PhpRbac related seems to be working (e.g. checking if a user has a role) _except_ for trying to get all roles/permissions (as children of root) using `{Entity}->children(1)` or `{Entity}->descendants(1)`. This is always returning an empty array, even though the exact same setup is working fine as it is hosted now.

Is there anything that could potentially be causing this?

**Comment by abiusx** [comment]
Yes I remember I fixed that, but I don’t know where I pushed the fixed code…
What version are you using?

**Comment by Mann-o** [comment]
I'm not certain which version I am using (I can't find anything in the source files to indicate this) but it was downloaded within the last 6 months.

**Comment by abiusx** [comment]
Can you post “Descendants” code for me?
I found this one:
    function Descendants($ID=null)
    {
        if ($ID===null) //from root
            $ID=1;
        $res = $this->{$this->Type ()}->DescendantsConditional(/\* absolute depths*/false, "ID=?", $ID );
        $out = array ();
        if (is_array ( $res ))
            foreach ( $res as $v )
                $out [$v ['ID']] = $v;
        return $out;
    }

**Comment by Mann-o** [comment]
```
function descendants($ID)
    {
        $res = $this->{$this->type ()}->descendantsConditional(/* absolute depths*/false, "ID=?", $ID );
        $out = array ();
        if (is_array ( $res ))
            foreach ( $res as $v )
                $out [$v ['Title']] = $v;
        return $out;
    }
```

**Comment by abiusx** [comment]
Try replacing it.
Collisions and root failure should be fixed in my version.
I remember I had a version that actually returned a PHP tree, but I can’t find it.

**Comment by abiusx** [comment]
Oh it seems to be here:
    private function CreateTree(&$list,$depth=1)
    {
        $res=array();
        $n=0;
        foreach ($list as $k=>$item)
        {
//          echo "Current item: {$item['Title']}<br/>";
            if ($item['Depth']==$depth)
            {
                unset($item['Lft']);
                unset($item['Rght']);
                unset($item['Depth']);
                $res[]=$item;
                unset($list[$k]);
//              echo "Used ".$item['Title']."<br>";
            }
            elseif ($item['Depth']>$depth)
            {
                end($res);
                $key=key($res);
//              echo "Going under ".$res[$key]['Title']."<br/>";
                $res[$key]['Children']=$this->CreateTree($list,$depth+1);
                reset($list); //the recursive call messes with internal pointer, reset it
            }
            else  //this node is finished
                break;

```
        $n++;
    }
```

//      echo "Going back...<br/><br/>";
        return $res;
    }

```
/**
 * Returns all nodes, in a tree-array structure
 * Every node has ID, Title, Description and might have an array of Children
 * @return array
 */
function All()
{
    $all=$this->Descendants();
    return array("ID"=>1,"Title"=>"root","Description"=>"root","Children"=>$this->CreateTree($all));
}
```

These are functions supposed to be added to the bottom of base.php
Using All should return an actual tree of roles/permissions.

**Comment by Mann-o** [comment]
Your `All()` function has `Dependants` capitalised whereas all of these types of functions are uncapitalised in my source. I think it may be easier if I just upgrade to the latest downloadable version and port the database data over?

**Comment by abiusx** [comment]
I’m not sure if these changes are merged into the latest branch.
You can send me the base file, or try decapitalizing these.
-A

**Comment by Mann-o** [comment]
I have decapitalised and added the functions to the bottom of my base.php file and used as follows:

```
$rbac = new PhpRbac\Rbac();
echo print_r($rbac->all(), 1);
```

...but I receive the following error: `Call to undefined method PhpRbac\Rbac::all()`.

I also tried:

```
$rbac = new PhpRbac\Rbac();
echo print_r($rbac->Roles->all(), 1);
```

...which returns the following error: `Call to undefined method RoleManager::all()`

Also, PhpStorm is complaining that `$this->descendants()` is missing the required parameter `$ID`.

**Comment by Mann-o** [comment]
Changed `descendants` function in rbac.php to the one you posted earlier - this still returns an empty array for me I'm afraid.

**Comment by abiusx** [comment]
Hmm. I think the wrappers need to be update too.
PHP RBAC is not PSR compliant, Jesse has created a wrapper around it.
The thing that you are calling is the wrapper, the code that I provided is for the core.

**Comment by Mann-o** [comment]
I'm going to try reinstalling PhpRbac and manually adding the roles/permissions again into a fresh database. I think something must have gone wrong with the export from where it is currently hosted since  the exact same setup is working fine there.

**Comment by derBoehm** [comment]
How can I update the wrapper? Need a treelist :)

Update: got it.

**Comment by abiusx** [comment]
You mean a nested PHP array, or a flat array that resembles a tree? I think I have the code for both somewhere, let me know and I’ll look it up.

**Comment by Mann-o** [comment]
With regards to reinstalling PhpRbac, this didn't work. Could it potentially be something related to the PHP version that was preinstalled on my Macbook (5.1.X)? I have since updated PHP but have not re-tested a fresh install.

In the meantime I have wrote manual functions in my API for handling the functionality that wasn't working correctly.

**Comment by abiusx** [comment]
I haven’t had a chance to look at the wrappers. Can you please point me to the file that you are using to call the wrapper on the repo? I can try to fix that but Jesse took care of providing the wrappers.
-A

**Comment by Mann-o** [comment]
`require_once 'PhpRbac/src/PhpRbac/Rbac.php';`

I am just creating a new instance of PhpRbac using `$rbac = new PhpRbac\Rbac();` and calling the relevant function: `$rbac->{Entity}->children(1)`

All of the other PhpRbac functions work fine.

**Comment by abiusx** [comment]
What happens when you try descendants?

**Comment by Mann-o** [comment]
Same thing unfortunately. They both work fine on the server the site is currently hosted at, but on my Macbook they return empty arrays. Possibly something related to either the old PHP version that was preinstalled on my Macbook (`5.3.x` I believe?) or the associated `php.ini`.

I have since updated to `5.6.19` but have not had an opportunity to retest using the original PhpRbac wrapper functions yet. I will give this a try in due course and update you.

**Comment by abiusx** [comment]
That is weird. Maybe your database structure is incorrect? Can you try it with a fresh RBAC database?

**Comment by Mann-o** [comment]
As mentioned earlier I did already attempt this but it did not work. Used a fresh install of PhpRbac and a fresh database with all of the roles/permissions/assignents etc added manually but the same issue occurred.

**Comment by abiusx** [comment]
By manually, do you mean directly added to the database or using the library?
Did you create anything specific in the database? Change any table settings? I need to be able to reproduce this to be able to fix it.

**Comment by Mann-o** [comment]
I reinstalled as per the instructions on PhpRbac.net, then used the library to run `{Entity}->add()`, `{Entity->assign()` etc, exactly how I did it the first time and how it is currently set up and running perfectly on the server it is hosted on. There is nothing specific in the database and I have not changed any table settings.

I understand the difficulty in narrowing down the issue when it is difficult to reproduce. I'll try re-using the PhpRbac functions now that I have upgraded to PHP `5.6.19` and see if the issue still remains. If it doesn't I would be happy to consider this issue resolved as it is likely something was amiss in either my old PHP version or `php.ini`.

**Comment by abiusx** [comment]
I don’t think it is a PHP issue, the library doesn’t really rely on any PHP functionality, but report back when you can. Thank you.

**Comment by Mann-o** [comment]
Unfortunately the same issue still occurs with PHP `5.6.19`. I have compared the database and setup to exactly what is hosted (and working) online now and everything is exactly the same, so I really do not understand what the issue could be.

In the meantime I am using the following snippet to return roles (for an API response) and it works fine, so I do not think this is a database issue:

```
$roles = array();
$conn = connectToDB();
$query = $conn->prepare('SELECT ID, Title, Description FROM phprbac_roles');
$query->execute();
while ($result = $query->fetch()) {
    if ($result['ID'] !== 1) {
        array_push($roles, array(
            'ID' => $result[ 'ID' ],
            'Title' => $result[ 'Title' ],
            'Description' => $result[ 'Description' ]
        ));
    }
}
return json_encode($roles);
```

**Comment by abiusx** [comment]
Hmm… I have no idea either unless we can reproduce this bug.

**Comment by Mann-o** [comment]
I'm going to close this issue and consider it a one-off which is specific to something I have messed up, even if we're not sure what it is that is broken. The application is running fine on my local machine now that I am using a couple of workarounds to directly get data from the `phprbac_*` tables.

Perhaps the next time I use PhpRbac on a fresh project I'll see if it occurs again but for now I would just consider this closed.
