### ISSUE TITLE
Can't find table or something like that?

### ISSUE THREAD

**Issue by wqking** [OWASP/rbac#98]
```
mysql --version
mysql.EXE  Ver 15.1 Distrib 10.1.13-MariaDB, for Win32 (AMD64)
```

```
php --version
PHP 5.6.23 (cli) (built: Jun 22 2016 12:15:20)
```

```php
database.config
<?php

$adapter="pdo_mysql";
$host="localhost";

$dbname="somedb";
$tablePrefix = "someprefix_";

$user="blah";
$pass="blah";
```

My test code,
```php
<?php
require_once '../lib3/vendor/autoload.php';

use \PhpRbac\Rbac as Rbac;

$rbac = new Rbac();
$result = $rbac->Roles->add('student', 'student');
echo $result;

?>
```

The $result is always 0 and no error message. And if I change the adapter to mysqli, it prints error message saying table somedb.somepreifx_roles can't be found.  
I've already setup the database correctly and the tables are there.

Thoughts?

**Comment by abiusx** [comment]
If tables are there you shouldn't get table not exists error. There's probably something wrong there.
-A

**Comment by wqking** [comment]
But how to diagnose it? phprbac doesn't give enough messages. Can I enable to see more verbose messages?

**Comment by wqking** [comment]
Damn, my fault. I wrongly replaced the table name with two underscores between the prefix and table name...
